"""Clean me helper."""

list_a = [
    "[a]",
    "[b]",
    "[c]",
    "[d]",
    "[e]",
    "[f]",
    "[g]",
    "[h]",
    "[i]",
    "[j]",
    "[1]",
    "[7]",
]


list_b = [
    "Allsvenskan play-offs",
    "Banned",
    "Champions ",
    "Chosen",
    "Cup Winners' Cup",
    "Did not play the next season",
    "Disqualified",
    "Entered 1988–89 European Cup",
    "Europa ",
    "European Cup",
    "Excluded",
    "FA Cup Winners",
    "Failed re-election",
    "Intertoto",
    "Invited",
    "Latin Cup",
    "League Champions",
    "League first round playoff",
    "Merged with ADO Den Haag to form FC Den Haag",
    "Merged with Blauw-Wit Amsterdam to form FC Amsterdam",
    "Mitropa",
    "Not admitted",
    "Not re-elected",
    "Qualification",
    "Qualification for the Europa League group stage",
    "Qualification for the Champions League group stage",
    "Qualification or relegation",
    "Qualification for the Europa League second qualifying round",
    "Qualified",
    "Provisionally relegated to Ligue 2 or lower due to financial difficulties",
    "PPG",
    "Readmitted",
    "Re-elected",
    "Relegated",
    "Relegation",
    "Reprieved from relegation",
    "Relegation to Ligue 2",
    "Resigned from league",
    "Segunda",
    "Serie ",
    "UEFA",
]


lookup_table: dict = {
    "AZ": "AZ Alkmaar",
    "AZ '67": "AZ Alkmaar",
    "PSV": "PSV Eindhoven",
    "Feijenoord": "Feyenoord",
    "Milan": "AC Milan",
    "Inter Milan": "Internazionale",
    "Inter": "Internazionale",
    "ChievoVerona": "Chievo",
    "Paris SG": "Paris Saint-Germain",
    "Deportivo de La Coruña": "Deportivo La Coruña",
    "FC Barcelona": "Barcelona",
    "CF Barcelona": "Barcelona",
    "Valencia CF": "Valencia",
    "Hércules CF": "Hércules",
    "Racing de Santander": "Racing Santander",
    "Celta de Vigo": "Celta Vigo",
    "CD Tenerife": "Tenerife",
    "Sevilla FC": "Sevilla",
    "UD Salamanca": "Salamanca",
    "RCD Espanyol": "Espanyol",
    "SD Compostela": "Compostela",
    "Sporting de Gijón": "Sporting Gijón",
    "CF Extramadura": "Extramadura",
    "CP Mérida": "Mérida",
    "CD Logroñés": "Logroñés",
    "AD Almería": "Almería",
    "Alavés": "Deportivo Alavés",
    "Albacete Balompié": "Albacete",
    "Atlético Bilbao": "Athletic Bilbao",
    "Betis": "Real Betis",
    "CD Castellón": "Castellón",
    "CD Málaga": "Málaga",
    "CE Sabadell FC": "Sabadell",
    "CF Extremadura": "Extremadura",
    "Celta": "Celta Vigo",
    "Cádiz CF": "Cádiz",
    "Córdoba CF": "Córdoba",
    "Elche CF": "Elche",
    "Granada CF": "Granada",
    "La Coruña": "Deportivo La Coruña",
    "Pontevedra CF": "Pontevedra",
    "RCD Español": "Español",
    "RCD Mallorca": "Mallorca",
    "Recreativo": "Recreativo de Huelva",
    "Sevilla CF": "Sevilla",
    "UD Las Palmas": "Las Palmas",
    "The Wednesday": "Sheffield Wednesday",
    "Leicester Fosse": "Leicester City",
    "Accrington": "Accrington Stanley",
    "Woolwich Arsenal": "Arsenal",
    "Birmingham": "Birmingham City",
    "Stoke": "Stoke City",
    "Small Heath": "Birmingham City",
    "Newton Heath": "Manchester United",
    "Juventus Cisitalia": "Juventus",
    "Ambrosiana-Inter": "Internazionale",
    "Ambrosiana": "Internazionale",
    "Madrid FC": "Real Madrid",
    "Atlético Aviación": "Atlético Madrid",
}
